/**
 * scripts/inject-env.js
 *
 * Build-time script that injects GOOGLE_MAPS_API_KEY into the frontend.
 *
 * Run via: npm run build
 * This script must execute before `firebase serve` or `firebase deploy`.
 *
 * Security note:
 *   The Maps JS API key is client-exposed by design — the browser must load it
 *   to render the map. Obscuring it in source is NOT the security control.
 *   The actual control is restricting the key in Google Cloud Console:
 *     Cloud Console > APIs & Services > Credentials > your Maps key
 *     > Application restrictions > HTTP referrers
 *     Add: https://your-project.web.app/*
 *     Add: https://your-project.firebaseapp.com/*
 *   A key restricted to your domain cannot be used by third parties even if read.
 *
 * Output: public/js/env-config.js   (gitignored — never committed)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// Load the .env file if present (for local development convenience).
// In CI/CD the variables are expected to already be in the environment.
try {
    const envPath = resolve(ROOT, '.env');
    const envContent = readFileSync(envPath, 'utf8');
    for (const line of envContent.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIndex = trimmed.indexOf('=');
        if (eqIndex === -1) continue;
        const key = trimmed.slice(0, eqIndex).trim();
        const value = trimmed.slice(eqIndex + 1).trim();
        if (key && !(key in process.env)) {
            process.env[key] = value;
        }
    }
} catch {
    // No .env file — rely on environment variables already being set.
}

const mapsKey = process.env.GOOGLE_MAPS_API_KEY || '';

if (!mapsKey) {
    console.warn('[inject-env] WARNING: GOOGLE_MAPS_API_KEY is not set.');
    console.warn('  Map functionality will be disabled until the key is provided.');
    console.warn('  Set it in .env (local dev) or Vercel Environment Variables (production).');
    // Do NOT exit — allow Vercel build to succeed; the key comes from env vars dashboard.
}

const geminiKey = process.env.GEMINI_API_KEY || '';
const geminiModel = process.env.GEMINI_MODEL || 'gemini-2.0-flash';

if (!geminiKey) {
    console.warn('[inject-env] WARNING: GEMINI_API_KEY is not set. Chat will not work.');
}

// Ensure the output directory exists.
mkdirSync(resolve(ROOT, 'public/js'), { recursive: true });

const outputPath = resolve(ROOT, 'public/js/env-config.js');
const outputContent = `/**
 * AUTO-GENERATED by scripts/inject-env.js — DO NOT EDIT OR COMMIT THIS FILE.
 * This file is gitignored. Re-run \`npm run build\` to regenerate it.
 *
 * Security: Client-exposed keys are protected by HTTP referrer restriction
 * configured in Google Cloud Console, not by source obscurity.
 */

// Expose environment config to the browser via a global object.
window.__ENV__ = {
    GOOGLE_MAPS_API_KEY: "${mapsKey}",
    GEMINI_API_KEY: "${geminiKey}",
    GEMINI_MODEL: "${geminiModel}"
};
`;

writeFileSync(outputPath, outputContent, 'utf8');
console.log(`[inject-env] public/js/env-config.js written successfully.`);
